### PR TITLE
Fix sand pipes

### PR DESCRIPTION
**Pull request by HybridDog**
The abm thought that not adjustable sand pipes are called "pipeworks:sand_tube" but they have more names, e.g. "pipeworks:sand_tube_1".
And l increased the picking up speed that you don't need to wait for the abm until dropped items get picked up.

https://github.com/VanessaE/pipeworks/pull/115/files?w=1

### CODE REVIEW

**Comment by VanessaE** [comment]
@Novatux Can you review this one?

**Comment by asl97** [comment]
is it really a good idea to have object look for pipe instead of the other way round?

**Comment by HybridDog** [comment]
>is it really a good idea to have object look for pipe instead of the other way round?

the object only looks for the pipes by searching a bit in a table and only when it gets activated or every https://github.com/VanessaE/pipeworks/pull/115/files?w=1#diff-a654fdaa469bf56ebf9c7fdc65bb6cf0R251 <update_interval> seconds, which could be set higher.

The other way round the pipes need to search for objects every second using get_objects_inside_radius, the active objects count of the abm wasn't used.

**Comment by asl97** [comment]
i suppose it would be ok if the object isn't moving but if it's moving, high update_interval would be bad.

moving as in `water pushing object`, `tnt explode and send item flying` or the `forever moving objects` (on the old gone landrush server, they were cool)

**Comment by HybridDog** [comment]
>if it's moving, high update_interval would be bad

l set the timer to the velocity of the object

**Comment by asl97** [comment]
the normal sand tube radius is just 2 which give it a diameter of 4.

setting the interval higher than 4 would make it possible for an object to move through the sand tube range/area without triggering it.

**Comment by HybridDog** [comment]
using an abm makes it possible, too

**Comment by asl97** [comment]
making it a sphere might break some setup, it would also make it hard to gauge the vacuum zone/area.

**Comment by HybridDog** [comment]
>i highly doubt there would be more than 100 known_vaccmings near each object

there could be more than 10 active objects near 10 vacuuming pipes

>making it a sphere might break some setup, it would also make it hard to gauge the vacuum zone/area.

lt was a sphere before, too, wasn't it?
The setup behaved strange, if you set the radius to 1, it was more than 1, so gauging it was very difficult.

**Comment by asl97** [comment]
10 objects near 10 vacuuming pipes would mean it could only be call 100 times, which should only take 0.25ms.
____
i am pretty sure https://github.com/HybridDog/pipeworks/commit/e25f4f84fc1953fe9bf5a01e1eb193ade9d25121#diff-a654fdaa469bf56ebf9c7fdc65bb6cf0L97 means it was a cube.

**Comment by HybridDog** [comment]
ok, it was a cube but you could configure the "radius"

**Comment by asl97** [comment]
telling people to configure the setting on the server to fix their tube setup is pretty bad way of doing things

to maintain backward compatibility, the default radius need to be increase to the diagonal of the square

ie:
```
>>> (8**2+8**2)**.5
11.313708498984761  # round up to 12
>>> (2**2+2**2)**.5
2.8284271247461903 # round up to 3
```
____
or it could just go back to the way it was (ie: a cube).

**Comment by HybridDog** [comment]
l can't imagine that changed vacuuming pipes ranges cause problems.

**Comment by asl97** [comment]
an example, a HUGE tree farm (eg: 80x80), with vacuuming pipes place perfectly spaced apart, harvest using chainsaw.

since the range is reduce cause it is in a sphere, there would be area where the pipe can't reach on the farm.

the whole piping system on the farm would have to be rearrange if the max is still 8.

even if it is increase to 12, the player would have to manually edit the 25 vacumming pipes that collect fallen stuff.

**Pull request closed without merging**
